config/routes.rb
Mebellook::Application.routes.draw do
  resources :styles do
    resources :units
  end

  get 'pages/home' => 'high_voltage/pages#show', id: 'home'

end

app/models/style.rb
class Style < ActiveRecord::Base
  has_many :units
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  validates :name, :image, :style_id, presence: true
  belongs_to :style
  mount_uploader :image, ImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :set_style, only: [:show, :edit, :update, :destroy]

  # GET /styles
  # GET /styles.json
  def index
    @styles = Style.all
  end

  # GET /styles/1
  # GET /styles/1.json
  def show
  end

  # GET /styles/new
  def new
    @style = Style.new
  end

  # GET /styles/1/edit
  def edit
  end

  # POST /styles
  # POST /styles.json
  def create
    @style = Style.new(style_params)

    respond_to do |format|
      if @style.save
        format.html { redirect_to @style, notice: 'Style was successfully created.' }
        format.json { render action: 'show', status: :created, location: @style }
      else
        format.html { render action: 'new' }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /styles/1
  # PATCH/PUT /styles/1.json
  def update
    respond_to do |format|
      if @style.update(style_params)
        format.html { redirect_to @style, notice: 'Style was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /styles/1
  # DELETE /styles/1.json
  def destroy
    @style.destroy
    respond_to do |format|
      format.html { redirect_to styles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_style
      @style = Style.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def style_params
      params.require(:style).permit(:name)
    end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]
  before_action :find_style

  # GET /units
  # GET /units.json
  def index
    @units = Unit.where('style_id = ?', @style.id).order(:created_at)
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = @style.units.build(unit_params)
    respond_to do |format|
      if @unit.save
        format.html { redirect_to style_unit_path(@style, @unit), notice: 'Unit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @unit }
      else
        format.html { render action: 'new' }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to  style_unit_path(@style, @unit), notice: 'Unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to style_units_path(@style) }
      format.json { head :no_content }
    end
  end

  private
    def find_style
      if params[:style_id]
        @style = Style.find(params[:style_id])
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name, :image, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/layouts/_about.html.haml
%section#about
  .row
    .panel.white
      %h3.fancy <span>О нас</span>
      .row
        .columns.medium-4
          %h3 История
          %p С 2008 года мы занимаемся внешнеэкономической деятельностью, помогая предпринимателям различных стран организовывать оптимальные схемы взаимодействия с Китаем. Обширный опыт работы с различными видами товаров и услуг позволяет нам оперативно реагировать на изменчивые рыночные тенденции КНР, и реализовывать для своих клиентов максимально эффективные методы ведения бизнеса.
        .columns.medium-4
          %h3 Философия
          %p Компания MebelLook это свежий и новый взгляд на выбор и покупку мебели. Строго ориентированный и индивидуальный подход в работе с каждым Нашим клиентом, это залог Вашего удачного денежного вложения. Мы в гарантированные сроки и без промедления реагируем на каждый заданный Вами вопрос,  и обеспечиваем полный и поэтапный контроль всех обстоятельств касающихся Вашей закупки.  Наш клиенты – это наши близкие друзья, все Ваши вопросы и проблемы мы решаем как свои собственные!
        .columns.medium-4
          %h3 Мотивация
          %p Почему именно мы? Выгодные условия сотрудничества, ответственное выполнение всех обязательств перед Вами, представление полной и достоверной информации о том что вы можете приобрести в Китае, грамотная консультация наших специалистов во всех вопросах будущей или уже совершенной вашей закупки, качественный сервис обслуживания на всех этапах сделки, готовность работы под индивидуальные требования каждого нашего клиента, нацеленная работа на результат. Результатом нашей работы – это ваше положительное мнение o нашe работe.
      .row
        .columns
          .alert-box.radius
            %h3
              Создан в 2008

app/views/layouts/_catalog.html.haml
%section#catalog
  .row
    .panel.white
      %h3.fancy <span>Каталог</span>
      .row
        .columns.small-offset-2.small-8
          %p  В представленной галерее мы предлагаем вам ознакомится с той малой долей того ассортимента который могут предложить вам мебельные  фабрики Китая.
          %p Цены даны с условием доставки и уплаты таможенных платежей в России.
          %ul
            %li Галерея  (все что есть 50 фото)
            %li Американский стиль (10 фото)
            %li Итальянский шик (10 фото)
            %li Французцкий прованс (10 фото)
            %li Арт-Деко (10 фото)
            %li Современный Hi-Tech (10 фото)

app/views/layouts/_clients.html.haml
%section#clients
  .row
    .panel.white
      %h3.fancy <span>Клиентам</span>
      .row
        .columns.medium-offset-2.medium-8
          %p Предлагаем вам ознакомиться с пошаговой инструкцией нашей работы.
      .row.list
        .columns.medium-offset-3.medium-6
          %h3 1. Удаленная работа
          %ul.no-bullet
            %li Почтовая переписка, телефонные переговоры
            %li Консультативная помощь по Мебельному Туру
            %li Предоставление всей необходимой информации для клиента
            %li Согласование даты приезда в Китай
            %li Оказание помощи различного характера (бронирование гостиниц, оформление виз, покупка авиабилетов и т.д.)
      .row.list
        .columns.medium-6
          %h3 2. Работа в Китае
          %ul.no-bullet
            %li Встреча в аэропорту
            %li Размещение в гостинице
            %li Сопроводительная работа по мебельным центрам и фабрикам
            %li Помощь в проведении переговоров и оформлении заказа
            %li Помощь в организации культурно-досугово отдыха
            %li Проводы в аэропорт
        .columns.medium-6
          %h3 4. Работа в России
          %ul.no-bullet
            %li Подготовка контейнера к таможенному оформлению в России
            %li Просчет всех будущих расходов для уплаты таможенных платежей
            %li Контролирование процесса на таможне
            %li Постановка контейнера на ЖД платформу
            %li Отправка контейнера по ЖД
            %li Автовывоз контейнера до адреса назначения
      .row.list
        .columns.medium-offset-3.medium-6
          %h3 3. Пост работа в Китае
          %ul.no-bullet
            %li Предоставление всей необходимой документации (упаковочный лист, расчеты оплат и т.д.)
            %li Контралирование сроов производста
            %li Своевременное информирование клиента о каких лобо изменениях или вопрасах касающихся его заказа
            %li Проверка товара, с последующем предоставлением отчета о проверке
            %li Согласование и утверждение отчета по проверке
            %li Проведение остаточных платежей
            %li Консолидирование товара на складе компании
            %li Оргонизация в подаче и загрузке контейнера
            %li Предоставление отчета по загрузке

app/views/layouts/_contact.html.haml
%section#contact
  .row
    #mail.panel.white
      .row.title
        %h3.fancy <span>Обратная связь</span>
      .row.details
        .columns.small-offset-1.small-10.medium-offset-1.medium-10
          %p Для того чтобы связаться с нами достаточно просто заполнить ниже прдставленную форму, и задать интересующий вас вопрос, мы гарантируем что в течении 24 часов обязательно свяжемся с вами и ответим на все интересующие вас вопросы:
          %form
            .row
              .small-12
                %input{type: "text", placeholder: "Имя"}
                %input{type: "text", placeholder: "Email"}
                %textarea{type: "text", placeholder: "Сообщение"}
                %input{:type => "submit", :value => "Отправить", :class => "button expand"}


                
              
                

app/views/layouts/_copyright.html.haml
%footer#copyright
  .row
    .columns.small-12
      © Copyright. All rights reserved. MebelLook.

app/views/layouts/_header.html.haml
%section#hero
  .container
    .row
      #intro.medium-offset-1.medium-7.columns
        .panel
          %h1= link_to ('Mebellook').html_safe, root_path
          %br
          %h3 Почему именно мы?
          %p Выгодные условия сотрудничества, ответственное выполнение.
          %a.button.tiny.transparent.radius{href: "#clients"} Узнать больше
          %a{href: "#contact"} Заказать Тур >

app/views/layouts/_services.html.haml
%section#services
  .row
    .panel.white
      %h3.fancy <span>Сервис</span>
      .row
        .columns.medium-offset-2.medium-8
          %p Всем своим клиентам мы предоставляем качественный и отличный сервис работы вне зависимости от времени и обстоятельств начала совместной работы.
          %p Грамотная консультация наших специалистов, позволит Вам рассчитать все риски и все ваши затраты еще до приезда в Китай. 
          %p Контролирование работы на всех ее этапах – это залог успеха качественного и успешного результата. Знания и опыт в работе с китайскими производителями, логистикой и работы таможенных органов Китая и России, гарантирует Вам получение ожидаемого результата как в вопросе качества так и в вопросе экономии денежных средств.
          %h4 Наши услуги:
      .row.services
        .columns.medium-3
          %h4 Консалт-работа
          %ul.no-bullet
            %li Информационная работа
            %li Помощь в организации приезда
            %li Сопровождение и помощь в оформлении заказа
            %li Пост обслуживание
        .columns.medium-3
          %h4 Дизайн
          %ul.no-bullet
            %li Разработка дизайн проекта
            %li Подбор мебели 
            %li Индивидуальная работа по дизайн-проекту клиента
            %li Помощь в оформлении интерьера
        .columns.medium-3
          %h4 Поиск
          %ul.no-bullet
            %li Удалена работа 
            %li Поиск  необходимой продукции
            %li Согласование цен
            %li Помощь в оформлении заказа
        .columns.medium-3
          %h4 Гарантии
          %ul.no-bullet
            %li Работа по договору
            %li Предоставление упаковочного листа
            %li Выставление инвойсов
            %li Изготовление отчетов (проверки, загрузки товара)

app/views/layouts/_topbar.html.haml
%header#topbar.fixed
  %nav.top-bar.shadow{data: {topbar: ""}}
    %ul.title-area
      %li.name
        %h1#logo
          = link_to (image_tag('house_logo.png',  width: '30') + image_tag('slogan_logo.png', width: '130')).html_safe, root_path
      %li.toggle-topbar.menu-icon
        %a{href: "#"}
          %span Menu
    %section{class: "top-bar-section"}
      %ul{class: "right"}
        %li
          %a{href: "#hero"} ГЛАВНАЯ
        %li
          %a{href: "#about"} О НАС
        %li
          %a{href: "#services"} "СЕРВИС"
        %li
          %a{href: "#catalog"} "КАТАЛОГ"
        %li
          %a{href: "#clients"} "КЛИЕНТАМ"
        %li
          %a{href: "#contact"} "ОБРАТНАЯ СВЯЗЬ"

app/views/layouts/application.html.haml
!!! 5
%html{lang: "ru"}
  %head
    %meta{charset: "utf-8"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    %title
      = content_for?(:title) ? yield(:title) : "Mebellook"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    = render 'layouts/topbar'
    = yield :top
    %main
      .row
        .columns.small-12.white
          = yield
    = yield :bottom
    = render 'layouts/copyright'
    = javascript_include_tag "application"

app/views/pages/home.html.haml
= content_for :top do
  = render 'layouts/header'
  = render 'layouts/about'
  = render 'layouts/services'

  %section#catalog
    .row
      .panel.white
        %h3.fancy <span>Каталог</span>
        .row
          .columns.small-12
            %p  В представленной галерее мы предлагаем вам ознакомится с той малой долей того ассортимента который могут предложить вам мебельные  фабрики Китая.
            %p Цены даны с условием доставки и уплаты таможенных платежей в России.
        .row
          .columns.small-12.filters
            %ul#filters
              %li
                %a{href: "?style_id=0#catalog"} Все стили
              - Style.all.each do |style|
                %li= link_to style.name, ("?style_id=" + style.id.to_s + "#catalog")
                

        .row
          %ul.small-block-grid-1.medium-block-grid-2.large-block-grid-3.clearing-thumbs{data: {clearing: ""}}
            - units = Style.find_by_id(params["style_id"]).try(:units) || Unit.all
            - units.each do |unit|
              %li.center
                %figure
                  %a{href: "#{unit.image_url(:large).to_s}"}
                    = image_tag unit.image_url(:thumb).to_s, data: {caption: "#{unit.name} #{unit.price.floor if unit.price.present?}"}
                    %figcaption
                      %h3= unit.name
                      %p= unit.price if unit.price.present?


= content_for :bottom do
  = render 'layouts/clients'
  = render 'layouts/contact'

app/views/styles/_form.html.haml
= form_for @style do |f|
  - if @style.errors.any?
    #error_explanation
      %h2= "#{pluralize(@style.errors.count, "error")} prohibited this style from being saved:"
      %ul
        - @style.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/styles/edit.html.haml
%h1 Editing style

= render 'form'

= link_to 'Show', @style
\|
= link_to 'Back', styles_path

app/views/styles/index.html.haml
.row
  .columns.small-12
    %h1 Стили Мебели
    %hr
    %ul.no-bullet
      - Style.all.each do |style|
        %li
          %h3= link_to style.name, style_path(style)
        %ul.small-block-grid-10
          - style.units.each do |unit|
            %li
              %a.th{href: "#{style_unit_path(style, unit.id)}"}
                = image_tag unit.image_url(:thumb).to_s
        %ul.button-group
          %li
            = link_to 'Edit', edit_style_path(style), class: 'button tiny'
          %li
            = link_to 'Добавить объект', new_style_unit_path(style_id: style.id), class: 'button success tiny'
        %hr

    = link_to 'Добавить стиль', new_style_path, class: 'button success'

app/views/styles/new.html.haml
%h1 New style

= render 'form'

= link_to 'Back', styles_path

app/views/styles/show.html.haml
%p#notice= notice

%h1
  = @style.name

%ul.small-block-grid-4
  - @style.units.each do |unit|
    %li
      %p
        = unit.name
      %a.th{href: "#{style_unit_path(@style, unit.id)}"}
        = image_tag unit.image_url(:thumb).to_s

%ul.button-group
  %li
    = link_to 'Back', styles_path, class: 'button secondary'
  %li
    = link_to 'Edit', edit_style_path(@style), class: 'button'
  %li
    = link_to 'Добавить объект', new_style_unit_path(style_id: @style.id), class: 'button success'
  %li
    = link_to 'Добавить стиль', new_style_path, class: 'button success'

app/views/units/_form.html.haml
= form_for [@style, @unit] do |f|
  - if @unit.errors.any?
    #error_explanation
      %h2= "#{pluralize(@unit.errors.count, "error")} prohibited this unit from being saved:"
      %ul
        - @unit.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.file_field :image
  .field
    = f.label :price
    = f.text_field :price
  .actions
    = f.submit 'Save'

app/views/units/edit.html.haml
%h1 Editing unit

= render 'form'

-# = link_to 'Show', @unit
\|
-# = link_to 'Back', style_units_path

app/views/units/index.html.haml
%h1= @style.name

%table
  %tr
    %th Название
    %th Фотография
    %th Стиль
    %th Стоимость $
    %th
    %th
    %th

  - @units.each do |unit|
    %tr
      %td= unit.name
      %td= image_tag unit.image_url(:thumb).to_s
      %td= unit.style.try(:name)
      %td= unit.price
      %td= link_to 'Просмотреть', style_unit_path(@style, unit.id), class: 'button tiny secondary'
      %td= link_to 'Редактировать', edit_style_unit_path(@style, unit), class: 'button tiny'
      %td= link_to 'Удалить', style_unit_path(@style, unit), :method => :delete, :data => { :confirm => 'Вы уверены?' }, class: 'button tiny alert'
        

%ul.button-group
  %li
    = link_to "New Unit", new_style_unit_path(@style), class: 'button success'
  %li
    = link_to 'Back', style_path(@style), class: 'button secondary'

app/views/units/new.html.haml
%h1 New unit

= render 'form'

= link_to 'Back', style_units_path

app/views/units/show.html.haml
%p#notice= notice

.units
  .columns.small-12.medium-9
    %h1
      = @unit.name
  .columns.small-12.medium-3
    %h1.right
      %span= "$" + @unit.price.to_s if @unit.price.present?
  %p
    %a.th
      = image_tag @unit.image_url(:large).to_s, data: {interchange: "[#{@unit.image_url(:small).to_s}, (small)], [#{@unit.image_url(:medium).to_s}, (medium)], [#{@unit.image_url(:large).to_s}, (large)]"}
  %h3
    %span Стиль:
    %span= @unit.style.try(:name)

%ul.button-group
  %li
    = link_to 'Назад', style_units_path(@style), class: 'button secondary'
  %li
    = link_to 'Редактировать', edit_style_unit_path(@style, @unit), class: 'button'
  %li
    = link_to 'Создать новый', new_style_unit_path(@style, @unit), class: 'button success'
  %li
    = link_to 'Удалить', style_unit_path(@style, @unit), :method => :delete, :data => { :confirm => 'Вы уверены?' }, class: 'button alert'